package at.aau.edu.appdev.messenger.model

val JOKES = listOf(
    "My teacher said he is gonna call my dad, i cant wait to meet him.",
    "I really hate waiting to die...\nIts taking a lifetime.",
    "How do you keep an Idiot waiting?",
    "What do sprinters eat before a race?\nNothing. They fast.",
    "Why did the computer get glasses?\nIt wanted to improve its website.",
    "What did the lawyer wear to court?\nA law suit.",
    "What's the best way to watch a fishing show?\nLive stream.",
    "Why did the police arrest the turkey?\nThey suspected foul play.",
    "What kind of tree fits in your hand?\nA palm tree.",
    "What do you call a can opener that doesn't work?\nA can't opener.",
    "Knock, knock! Who's there? Spell. Spell who? W-H-O.",
    "Knock, knock! Who's there? Ash. Ash who? Bless you!",
    "My boss told me to have a good day, so I went home.",
    "When does a joke become a dad joke?\nWhen it leaves and never comes back.",
    "My dad wasn't absent, he was just fathering remotely.",
    "I don't have a carbon footprint.\nI just drive everywhere.",
    "What's yellow and can't swim?\nA bus full of children.",
    "Why don't cannibals eat clowns?\nBecause they taste funny.",
    "I hope Death is a woman.\nThat way it will never look at me twice.",
    "The doctor gave me one year to live.\nAfter I shot him the judge gave me 15.",
    "How do you get a nun pregnant?\nDress her up like an altar boy.",
    "Why can’t women ski?\nThere’s no snow in the kitchen.",
    "What do you call an IT Teacher who likes kids?\nA PDF Fil.e",
    "What would Martin Luther King be if he wasn’t black?\nAlive.",
    "What do you call Jewish Pokemon trainer?\nAsh.",
    "What should you give a sick lemon?\nLemon aid.",
    "What do you call a polar bear in the jungle?\nLost.",
    "Can February march?\nNo, but April may!",
    "What do you call a fake noodle?\nAn im-pasta!",
    "Why couldn't the bicycle stand on its own?\nIt was two tired!",
    "What did one ocean say to the other?\nNothing, it just waved."
)